export const CATEGORY_ADD = "CATEGORY_ADD";
export const CATEGORY_ADD_FAIL = "CATEGORY_ADD_FAIL";
export const PRODUCT_ADD = "PRODUCT_ADD";
export const PRODUCT_ADD_FAIL = "PRODUCT_ADD_FAIL";
export const PRODUCT_DETAIL = "PRODUCT_DETAIL";
export const CATEGORY_ADD_LIST = "CATEGORY_ADD_LIST";
export const CATEGORY_FAIL_LIST = "CATEGORY_FAIL_LIST";
export const CATEGORY_ID="CATEGORY_ID";