module.exports = {
  Driver: require("./driver"),
  Location: require("./locations"),
  Ride: require("./ride"),
  Notification: require("./notification"),
  ReasonForCancelling: require("./reasons"),
  RideHistory: require("./rideHistory"),
  CancelReasonBy: require("./cancelreason"),
  Admin: require("./admin"),
  Consumer: require("./consumer"),
  VehicleType: require("./vehicleType"),
  RatesType: require("./ratesType"),
  SurgeCharges: require("./surCharges"),
  BaseCharges: require("./baseCharges"),
  Rating: require("./rating"),
  Region: require("./region"),
  Vehicles: require("./allVehicles"),
  FavouriteAddressForConsumer: require("./favAddressForConsumer"),
  CouponCodes: require("./couponCode"),
  ContactUs: require("./contactUs"),
  MultiNotification: require("./multiNotification"),
  RideType : require("./rideType"),
  PromotionalBanners : require("./promotionalBanner"),
  ContactInSOS : require("./contatctData"),
  PromoCodeLogs : require("./promoCodelogs")
};
